package org.mariaavila.stalingrad.model;

import java.util.ArrayList;
import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * SimulationInput
 */

public class SimulationInput   {

  @Valid
  private List<String> tanks = new ArrayList<>();

  private String mapId;

  public SimulationInput tanks(List<String> tanks) {
    this.tanks = tanks;
    return this;
  }

  public SimulationInput addTanksItem(String tanksItem) {
    this.tanks.add(tanksItem);
    return this;
  }

  /**
   * Get tanks
   * @return tanks
  */
  @NotNull
  public List<String> getTanks() {
    return tanks;
  }

  public void setTanks(List<String> tanks) {
    this.tanks = tanks;
  }

  public SimulationInput mapId(String mapId) {
    this.mapId = mapId;
    return this;
  }

  /**
   * Not required to create a Map(is Autogenerated by the BD)
   * @return mapId
  */
  @NotNull
  @Size(max=50) 
  public String getMapId() {
    return mapId;
  }

  public void setMapId(String mapId) {
    this.mapId = mapId;
  }
}

